feat: accept NA in countElements; see #61
rformassspectrometry/MetaboCoreUtils pull request #62
Opened 2023-08-01 19:13 UTC by sgibb

This PR allows `NA`s in `subtractElements` and `addElements` by handling `NA`s in `countElements` (problem described in #61 )

`subtractElements("H2O", NA)` returns `"H2O"`. Or should it return `NA`?

Unfortunately it introduce a strange behaviour for `containsElements`:

```r
containsElements("H2O", NA)
# [1] TRUE
```

IMHO `containsElements("H2O", NA)` should return `FALSE` or `NA`.

@jorainer, @michaelwitting any suggestion for the expected behaviour?

2023-08-02 07:24 UTC, jorainer commented
IMO the following would make sense:

`containsElements("H2O", NA)` should return `NA`
`substractElement("H2O", NA)` returns `NA_character_`
`containsElements("H2O", "")` should return `FALSE` (same as e.g. `containsElements("H2O", "Z")`)

with the current PR you're also reporting `TRUE` for `containsElements("H2O", "Z")`... thus, it always returns `TRUE` even if the provided element does not exist...

2023-08-02 07:27 UTC, jorainer requested changes
See comment - basically I would suggest to change the behavior to return `NA` for `countElements("H2O", NA)` as well as for `subtractElement` or `addElement` where a `NA` is provided.

2023-08-02 18:50 UTC, sgibb commented
> `containsElements("H2O", NA)` should return `NA` `substractElement("H2O", NA)` returns `NA_character_` 

done!

> `containsElements("H2O", "")` should return `FALSE` (same as e.g. `containsElements("H2O", "Z")`)
> with the current PR you're also reporting `TRUE` for `containsElements("H2O", "Z")`... thus, it always returns `TRUE` even if the provided element does not exist...

This wasn't introduced by this PR but is a bug that was/is already present. I add an issue #63 .

IMHO we could close #61 with this PR and fix #63 in another one.

2023-08-04 05:52 UTC, jorainer approved these changes
Thanks @sgibb for the PR! Can you please also bump the version and add an entry to the NEWS file? apart from that all OK from me to merge.

2023-08-04 12:53 UTC, merged